url: https://karpatsolutions.ca
baseurl: /agency-jekyll-theme/

# Site settings
title:  Karpat Solutions
email: zoltan.marton@karpatsolutions.ca
description: "Simulation & Computational Engineering Consultant | CAD • CFD • FEA • Algorithms"


# Team names, titles and social links
people:
- name: Zoltan Marton
  pic: 1
  position: Founder / Consultant
  social:
    - title: X
      url: https://x.com/mart18786
    - title: Linkedin
      url: https://www.linkedin.com/in/zoltanm1923901/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Ottawa, ON, Canada

# Build settings
markdown: kramdown
permalink: pretty
