url: https://karpatsolutions.ca
baseurl: ""

plugins:
  - jekyll-sitemap

# Site settings
title: Karpat Solutions
logo: "img/logos/karpat-logot.png"  
email: zoltan.marton@karpatsolutions.ca
description: "Simulation & Computational Engineering Consultant | CAD • CFD • FEA • Algorithms"

# Team members
people:
  - name: Zoltan Marton
    pic: 1
    position: Founder / Consultant
    social:
      - title: linkedin-in
        url: https://www.linkedin.com/in/zoltanm1923901/
      - title: youtube
        url: https://www.youtube.com/@ZoltanMarton-KarpatSolutions
      - title: x
        url: https://x.com/mart18786
      - title: github
        url: https://github.com/ZMatrix253

# Social networks
social:
  - title: linkedin-in
    url: https://www.linkedin.com/in/zoltanm1923901/
  - title: youtube
    url: https://www.youtube.com/@ZoltanMarton-KarpatSolutions
  - title: x
    url: https://x.com/mart18786
  - title: github
    url: https://github.com/ZMatrix253

# Postal address
address:
  - line: Ottawa, ON, Canada

# Build settings
markdown: kramdown
permalink: pretty


