url: https://karpatsolutions.ca
baseurl: ""

# Site settings
title: Karpat Solutions
email: zoltan.marton@karpatsolutions.ca
description: "Simulation & Computational Engineering Consultant | CAD • CFD • FEA • Algorithms"

# Team members
people:
  - name: Zoltan Marton
    pic: 1
    position: Founder / Consultant
    social:
      - title: x            # Font Awesome 6 brand icon for X/Twitter
        url: https://x.com/mart18786
      - title: linkedin     # Font Awesome 6 brand icon for LinkedIn
        url: https://www.linkedin.com/in/zoltanm1923901/
      - title: youtube      # Font Awesome 6 brand icon for YouTube
        url: https://www.youtube.com/@ZoltanMarton-KarpatSolutions
      - title: github       # Font Awesome 6 brand icon for GitHub
        url: https://github.com/ZMatrix253

# Footer / general social links
social:
  - title: linkedin
    url: https://www.linkedin.com/in/zoltanm1923901/
  - title: youtube
    url: https://www.youtube.com/@ZoltanMarton-KarpatSolutions
  - title: x
    url: https://x.com/mart18786
  - title: github
    url: https://github.com/ZMatrix253

# Postal address
address:
  - line: Ottawa, ON, Canada

# Build settings
markdown: kramdown
permalink: pretty
